### ISSUE TITLE
fatal: not a git repository: .git (while testing extracted tarball with cabal new-build, etc.)

### ISSUE THREAD

**Issue by byorgey** [haskell-CI/haskell-ci#154]
My build is failing with this error.  Here's a sample:

```
[1 of 1] Compiling Main             ( repl/REPL.hs, /tmp/dist-test.WE4m/dist-newstyle/build/x86_64-linux/ghc-8.0.2/disco-0.1.0.0/build/disco/disco-tmp/Main.o )
Linking /tmp/dist-test.WE4m/dist-newstyle/build/x86_64-linux/ghc-8.0.2/disco-0.1.0.0/build/disco/disco ...
fatal: Not a git repository (or any of the parent directories): .git
readCreateProcess: git "ls-files" "test" (exit 128): failed
```

The same error occurs in other places as well.  See here for more detail:

https://travis-ci.org/disco-lang/disco/jobs/366685610#L909

The rest of the build seems to be fine, but this error is popping up in several of the test components and I have no idea what it means or what might cause it.  I just (yesterday) created the `.travis.yml` by running `make_travis_yml_2.hs`.  Ideas?

**Comment by hvr** [comment]
Well, your Setup.hs file (https://github.com/disco-lang/disco/blob/master/Setup.hs) invokes `git ls-files test`... and some assumption about the Git filesystem environment doesn't hold...

general comment: ideally, a `cabal sdist` action ought to have someting like a fix-point; i.e. if you 

`cabal get foo` && `cd foo-*/` && `cabal sdist`

you should ideally be able to reach a fixpoint.

**Comment by byorgey** [comment]
Aha, thanks, I had totally forgotten about the custom `Setup.hs`.  So what do you think is the "right" way to deal with something like this (i.e. automating the addition of a lot of things to extra-src-files)?

**Comment by hvr** [comment]
Personally, I tend to move this outside of the cabal `sdist` logic, as otherwise I'm forced to use a custom setup which everyone installing the package needs to pay (additional solving & compilation cost, additional `setup-depends` maintenance overhead, etc) just for a bit more convenience for the single maintainer.

So basically I'd use a script which is capable of updating the `extra-src-files` by modifying the `.cabal` file and have it VCS tracked (and this can be checked by CI if desired). In its simplest form, all this needs is some magic markers in the `.cabal` file to delimit the section that shall be updated by the script. I do realize this shifts a little bit of inconvenience away from the consumers to the package maintainer; otoh this imho is amortized by not having to deal w/ the maintenance of a custom setup script...

**Comment by byorgey** [comment]
I see, makes sense.  Thanks for the advice!

**Comment by phadej** [comment]
@byorgey for the record, e.g. `Cabal` the lib uses https://github.com/haskell/cabal/blob/master/cabal-dev-scripts/src/GenExtraSourceFiles.hs

**Comment by byorgey** [comment]
@phadej Thanks!
