### ISSUE TITLE
Does haskell-ci support package.yaml?

### ISSUE THREAD

**Issue by hanjoosten** [haskell-CI/haskell-ci#248]
In our project, we use hpack to generate a .cabal file from our package.yaml file. I would love to use haskell-ci to generate a .travis-ci file. In the documentation I see no clues on how to do that. Is this supported?

**Comment by hvr** [comment]
We don't really support .cabal file preprocessors as those wouldn't be supported by cabal either (and it's unlikely cabal will have support for it any time soon due to the engineering cost of doing this correctly as it's very tricky getting this right as well as avoiding significant performance/latency penalties; instead we're focusing on improving the `.cabal` format to reduce the incentive for wanting to use `.cabal` preprocessors in the first place).

So I'd think you'd already run into problems with cabal if you don't have already a means to materialize the `.cabal` files before invoking `cabal v2-build`, as `cabal.project` would be referring to packages not having their `.cabal` files synthesized. And you'd also cause problems for cabal users who want to depend directly on your Git repository via cabal's [`source-repository-package`](https://cabal.readthedocs.io/en/latest/nix-local-build.html#specifying-packages-from-remote-version-control-locations).

**Comment by hanjoosten** [comment]
The reason we use hpack is that we have a large (and frequently changing) set of datafiles that we want to come with the library. At least some time ago wildcards weren't supported for data files in .cabal files.

**Comment by hanjoosten** [comment]
Ah, I see that from cabal 2.4, this is supported.

**Comment by hvr** [comment]
yes, I was gonna point out https://cabal.readthedocs.io/en/latest/file-format-changelog.html#cabal-version-2-4 :-)

**Comment by hanjoosten** [comment]
thanks
