### ISSUE TITLE
Builds with GHC 8.8.2 failing due to broken binary-0.8.7.0?

### ISSUE THREAD

**Issue by sjakobi** [haskell-CI/haskell-ci#360]
In https://github.com/haskell/containers/pull/701, I've regenerated the Travis config with a 8.8.2 job. For some reason that job fails during the `cabal v2-freeze` step, reporting a broken installed `binary` package:

```
$ ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH}
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: containers-0.6.2.1 (user goal)
[__1] trying: base-4.13.0.0/installed-4.1... (dependency of containers)
[__2] trying: containers-tests-0 (user goal)
[__3] rejecting: containers-tests:!test (constraint from config file, command line flag, or user target requires opposite flag selection)
[__3] trying: containers-tests:*test
[__4] trying: test-framework-quickcheck2-0.3.0.5 (dependency of containers-tests *test)
[__5] trying: test-framework-0.8.2.0 (dependency of containers-tests *test)
[__6] trying: regex-posix-0.96.0.0 (dependency of test-framework)
[__7] trying: regex-base-0.94.0.0 (dependency of regex-posix)
[__8] trying: text-1.2.4.0/installed-1.2... (dependency of regex-base)
[__9] next goal: binary (dependency of text)
[__9] rejecting: binary-0.8.7.0/installed-0.8... (package is broken)
[__9] rejecting: binary-0.8.8.0, binary-0.8.7.0, binary-0.8.6.0, binary-0.8.5.1, binary-0.8.5.0, binary-0.8.4.1, binary-0.8.4.0, binary-0.8.3.0, binary-0.8.2.1, binary-0.8.2.0, binary-0.8.1.0, binary-0.8.0.1, binary-0.8.0.0, binary-0.7.6.1, binary-0.7.6.0, binary-0.7.5.0, binary-0.7.4.0, binary-0.7.3.0, binary-0.7.2.3, binary-0.7.2.2, binary-0.7.2.1, binary-0.7.2.0, binary-0.7.1.0, binary-0.7.0.1, binary-0.7.0.0, binary-0.6.4.0, binary-0.6.3.0, binary-0.6.2.0, binary-0.6.1.0, binary-0.6.0.0, binary-0.5.1.1, binary-0.5.1.0, binary-0.5.0.2, binary-0.5.0.1, binary-0.5, binary-0.4.5, binary-0.4.4, binary-0.4.3.1, binary-0.4.3, binary-0.4.2, binary-0.4.1, binary-0.4, binary-0.3, binary-0.2, binary-0.10.0.0, binary-0.9.0.0 (conflict: text => binary==0.8.7.0/installed-0.8...)
[__9] fail (backjumping, conflict set: binary, text)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: text, binary, test-framework, base, test-framework-quickcheck2, containers-tests, containers-tests:test, regex-posix, regex-base, containers
Try running with --minimize-conflict-set to improve the error message.
```

Any idea what could be going on?

Sorry if this is the wrong place to report this – I'd be happy to move this to a more appropriate place.

**Comment by RyanGlScott** [comment]
I suspect this is because (1) `text` depends on `binary` and (2) `binary` depends on `containers`, so in order to construct a valid build plan for the `containers` library itself, you would need to rebuild both `text` and `binary`. However, `text` is a boot library on GHC 8.8 and later, and by default `haskell-ci` forces build plans to use the already installed versions of boot libraries. This creates a conflict with a build plan that needs to rebuild `text` (since boot libraries cannot be reinstalled), hence the `fail (backjumping, conflict set: binary, text)` diagnostic.

You might try putting `installed: +all -binary -text` in your `cabal.haskell-ci` file to see if that fixes the issue.

**Comment by sjakobi** [comment]
Many thanks @RyanGlScott. Indeed your suggestion for the `installed:` line fixes the issue!

Could you expand a bit on how (and possibly why) the status of `text` changed in 8.8? I can't find anything related  at http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/8.8.1-notes.html or https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.8.

**Comment by RyanGlScott** [comment]
If I recall correctly, the version of `Cabal` that shipped with GHC 8.8.1 gained a `parsec` dependency, and `parsec` depends on `text.`

**Comment by sjakobi** [comment]
Hmm, the additional dependencies on `parsec` and `text` in `Cabal` happened already in `Cabal-2.2` which shipped with 8.4 according to https://gitlab.haskell.org/ghc/ghc/wikis/commentary/libraries/version-history.

So it seems that something else must have happened in 8.8 and I wonder what it is.

**Comment by RyanGlScott** [comment]
In that case, here is a different hypothesis. `cabal-install`'s solver usually tries to pick the latest Hackage versions of each library dependency (assuming they don't conflict with `installed` constraints). The latest Hackage version of `text` is 1.2.4.0, which is more recent than what GHC 8.6.5 and older ship with. As a result, `cabal-install` has no issue with installing `text-1.2.4.0` since it decides not to use the bundled version of `text` (in the particular case of GHC 8.6.5, that's `text-1.2.3.1`).

The story is different for GHC 8.8.1, since it bundles `text-1.2.4.0`. My guess is that this confuses `cabal-install`'s solver and makes it unwilling to install `text-1.2.4.0` from Hackage, instead preferring to use the bundled version.

**Comment by sjakobi** [comment]
Ooh, well that sounds pretty plausible!

Again, many thanks for you help @RyanGlScott! :)

**Comment by phadej** [comment]
For the record, explanation why `text` caused problems with GHC-8.8.1 is because there were install plans on 8.6.5 without `text`. But e.g. the only GHC-8.8 compatible `regex-base` (see changelog: https://hackage.haskell.org/package/regex-base-0.94.0.0/changelog) also happen to depend on `text` so it's pulled in:

The interesting bit of plan difference (`cabal-plan diff`)

```diff
           ├─ regex-posix 0.95.2 -> 0.96.0.0
           │  └─ regex-base 0.93.2 -> 0.94.0.0  <--- here
           │     ├─ bytestring 0.10.8.2 -> 0.10.10.0
           │     │  └─ deepseq-1.4.4.0 ┄┄
           │     ├─ containers-0.6.2.1 ┄┄
           │     ├─ mtl-2.2.2
           │     │  └─ transformers-0.5.6.2 ┄┄
+++        │     └─ text -> 1.2.4.0
           └─ xml 1.3.9 -> 1.3.14
              ├─ bytestring 0.10.8.2 -> 0.10.10.0 ┄┄
+++           └─ text -> 1.2.4.0 ┄┄
```
