### ISSUE TITLE
GHC 8.0.2 job fails due to combination of -Werror=missing-methods and -Werror

### ISSUE THREAD

**Issue by sjakobi** [haskell-CI/haskell-ci#377]
`haskell-ci` seems to add `-Werror=missing-methods` to all jobs, despite it being supported (AFAIK) only for GHC >= 8.2.

This causes a warning with GHC 8.0.2: https://travis-ci.org/github/hedgehogqa/haskell-hedgehog/jobs/670602896#L752-L753

When I additionally use `-Werror`, that warning causes the job to fail: https://travis-ci.org/github/hedgehogqa/haskell-hedgehog/jobs/671113793#L838-L842

**Comment by phadej** [comment]
Thanks for catching this up. Does https://github.com/haskell-CI/haskell-ci/pull/378 fix it for you?

---

Note however, `haskell-ci` is configurable. There is an option
```
--error-missing-methods
```
which would take also `none`. So you **don't need to manually edit** `.travis.yml`. There are hardly any reason to edit them manually. Often also broken features could be turned off.

---

Another comments:

`haskell-ci regenerate --copy-fields=all` in `bin/regenerate.hs` is too complicated.

Just generate `haskell-ci --copy-field=all cabal.project` once, and the `haskell-ci regenerate` **will** pick up the previous config. Alternatively you can put that and (other options) into `cabal.haskell-ci`.

There is also configuration option `--local-ghc-options`, which (`haskell-ci` uses itself and) I'd rather recommends for CI (i.e. `--local-ghc-options=-Werror`) and not put `-Werror` into `cabal.project` used for development. I find it very inconvenient. (If users like it, they could add that to `cabal.project.local`).

**Comment by sjakobi** [comment]
Thank you very much for the very fast fix, @phadej! #377 seems to do the trick! :)

And many thanks for all the advice! I switched https://github.com/hedgehogqa/haskell-hedgehog/pull/376 to use `haskell-ci --copy-field=all cabal.project`. `--local-ghc-options` looks very useful too – I might use that for my own projects!

**Comment by sjakobi** [comment]
As an aside, would you happen to know anything about the Travis "checks" recently not showing up on GitHub PRs, as for example in https://github.com/hedgehogqa/haskell-hedgehog/pull/376? I see only the AppVeyor build listed there. More concerningly commits were marked green, when the Travis build was in fact failing.

I very much hope that this degradation of service is only temporary – especially now that I begin to understand the full power of `haskell-ci`! :)

**Comment by phadej** [comment]
In fact I do. https://www.traviscistatus.com/incidents/rx6fhs3wqcln is still happening.

Travis support advised to migrate to GitHub apps integration, i.e. use https://travis-ci.com/account/repositories (note the `.com`). There is also migrate functionality https://travis-ci.com/account/migrate to move old service-hook based integrations (like the one `haskell-ci` uses now) to new apps one. It says Beta, but I was told that's only because you'll loose build history in the migration. The new apps integration itself should be "production ready". (I.e. it's the migration tool which is beta, not the integration method). You need to be an admin of the repositories do to those changes though. I'm also lazy, and didn't migrate stuff I could.

Travis people are looking into the reporting issue, so it will hopefully fix by itself later. I reported and got replies just this week, so it's quite recent still.

**Comment by sjakobi** [comment]
Thanks again! :)

I'll give the migration a try if the issue isn't resolved soon.
