### ISSUE TITLE
GHA: irc notifications are not issued if build job fails

### ISSUE THREAD

**Issue by phadej** [haskell-CI/haskell-ci#437]
Due dependency, the notification job is simply not run...

https://github.com/haskell-CI/haskell-ci/runs/1585115378?check_suite_focus=true

**Comment by RyanGlScott** [comment]
Oops! I could have sworn that I tested the failure notification before landing this, but it seems that I didn't test thoroughly enough.

Reading the GitHub Actions docs further, it looks like that the [default behavior for `jobs.<job_id>.needs`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idneeds) is for failing jobs to cancel any dependent jobs. This can apparently be changed if the right form of conditional expression is used, such as in [the following example](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-not-requiring-dependent-jobs-to-be-successful):

```yaml
jobs:
  job1:
  job2:
    needs: job1
  job3:
    if: always()
    needs: [job1, job2]
```

Here, `job3` always runs, regardless of whether `job1` or `job2` were successful.

Of course, our situation is a bit more complicated than this example, since we are already using a conditional expression in the `irc` job (e.g., `if: ${{ github.repository == 'haskell-CI/haskell-ci' }}`). I wonder what the simplest way to convince GitHub Actions to always run the `irc` job would be? I'm tempted to try something like this:

```
if: ${{ always() and (github.repository == 'haskell-CI/haskell-ci') }}
```

**Comment by phadej** [comment]
If something like 

```
if: ${{ always() and (github.repository == 'haskell-CI/haskell-ci') }}
```

works , then it's fine. This repository notifies `#haskell-lens` so feel free to open experiments.

---

Not updating test outputs is one way to make jobs fail :) (and to test the failure behavior)

**Comment by RyanGlScott** [comment]
> What syntx is those expression. Aren't they some pseudo JavaScript? Do I want to know?

This is GitHub Actions' [context and expression syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions). And now that I look closer, my attempt at guessing the syntax was incorrect—I should have used `&&` instead of `and`, per the [Operators section](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#operators).
