### ISSUE TITLE
Haddocks-checking of test suites and benchmarks seems unnecessary

### ISSUE THREAD

**Issue by sjakobi** [haskell-CI/haskell-ci#605]
I'm seeing some weird CI failures after regenerating a GitHub Actions config with the current `haskell-ci` `master`: https://github.com/haskell-unordered-containers/unordered-containers/pull/477

Apparently the enabling of the `--haddock-all` option (via https://github.com/haskell-CI/haskell-ci/pull/585) means that incorrect haddock syntax in benchmarks now cause CI failures.

Frankly I don't understand the purpose of these checks – I don't think _anyone_ cares about the haddocks of benchmark components.

So I'd like to request that `haskell-ci` doesn't check the haddocks of `test-suite` and `benchmark` components by default.

**Comment by phadej** [comment]
Discuss with @andreasabel, he added `--haddock-all`.

**Comment by andreasabel** [comment]
I think that checking all haddocks is a good default, but one should be able to opt out of this.  We'll likely need a new configuration field for that.

**Comment by sjakobi** [comment]
> We'll likely need a new configuration field for that.

How about a flag `haddock-all` to toggle `cabal`'s `--haddock-all` option?

**Comment by andreasabel** [comment]
Or `haddock-what` with possible monoidal values `all` (default), `executables` etc.

**Comment by sjakobi** [comment]
Both would be fine for me. Of course, I still think that by default, the `haddock` steps should be limited to the libraries.

**Comment by phadej** [comment]
I found a good reason to revert the `--haddock-all` change: modules with `inspection-testing` tests fail miserably when you try to `haddock` them.

I'm waiting two weeks for a patch (either to simply restricting haddock to libraries only, or more granular), otherwise I'll revert https://github.com/haskell-CI/haskell-ci/commit/2922aa508d36937cd2de5488159c43de6894e5d8

**Comment by andreasabel** [comment]
Im a fine with a revert.  I can patch in the haddock step in the `hackage-server` CI with a bit of extra work.
I still think that the `haddock` step should be forced if there is a `haddock` configuration in the `cabal.haskell-ci` file even if there is no library in the project.  But this might be harder to implement if `haddock: True` isn't distinguished from no `haddock:` field.

**Comment by phadej** [comment]
I was probably unclear, I'll welcome a separate config option (say `haddock-all: True/False` or `haddock-components: all|lib|lib exes|...`). But as `--haddock-all` is blocking upgrade and I'm short on time myself, I'll be forced to revert `--haddock-all` patch instead of implementing above additional feature myself.

**Comment by andreasabel** [comment]
Yes, understood, thanks for the clarification.  
Atm, I cannot dive into adding this option, so I approve reversal.

**Comment by RyanGlScott** [comment]
I've also ran into another situation in `singletons`' CI where `--haddock-all` can trigger a `cabal` bug—see haskell/cabal#5423. I am working around the issue by running `cabal haddock all` instead of `cabal haddock all --haddock-all`. (It's a bit weird that those commands don't do the same thing, but eh.)

**Comment by phadej** [comment]
Resolved in #613

**Comment by RyanGlScott** [comment]
Thanks, @phadej!
